"""Public compatibility layer for the split ast_nodes package."""

from __future__ import annotations

from ..errors import (
    CompileError,
    EmitError,
    LiteralMismatchError,
    NeedSyntaxError,
    NeedTargetError,
    OperandCountError,
    OperandTypeError,
    RuleConditionError,
    RuleExecutionError,
    RuleInstructionError,
    SymbolPendingError,
    UnknownNeedTypeError,
)
from ..lexer import Lexer, Token

from .node_constants import (
    IDENT_RE,
    KNOWN_NEED_TYPES,
    NEED_NORMALIZE,
    CONDITION_NAMES,
    EMIT_MODES,
    RESERVED_INSTRUCTION_NAMES,
    HEX_BYTE_RE,
)

from .node_info import (
    TypeInfo,
    SubRegisterInfo,
    RegisterInfo,
    SymbolInfo,
    WordInfo,
    StackInfo,
)

from .node_syntax import (
    InstructionNode,
    MacroNode,
    NeedNode,
    LiteralNeedNode,
    OperandNode,
    RefNode,
    IntNode,
    StringNode,
    ConditionNode,
    CheckNode,
    EmitNode,
    ErrorNode,
    OffNode,
    OnNode,
    CaseNode,
    SwitchNode,
    CallNode,
    NonsfamilyNode,
    MemskipNode,
    MarkNode,
    MultipleNode,
    StrictNode,
    CalcdistNode,
    AssignNode,
    PendingNode,
)

from .node_rules import (
    CompiledRule,
    RuleNode,
    Program,
)

from .node_macros import (
    expand_macro_instructions,
    expand_macro_call,
    parse_macro_call_args,
    substitute_instruction,
    substitute_tokens,
    clone_instruction,
    instruction_source,
    tokens_to_source,
    token_to_source,
    needs_space,
)

from .node_compile import (
    compile_need_instruction,
    compile_rule_body,
    compile_rule_instruction,
    compile_switch,
    compile_case,
    compile_on,
    compile_emit,
    compile_error,
    parse_condition,
    split_condition_operator,
    parse_expr,
    parse_case_value,
    parse_bit_size,
    parse_cbits_part,
    split_spaces,
    tokens_with_head,
    strip_trailing_colon,
    ensure_no_children,
    ensure_no_args,
)

from .node_utils import (
    split_token_groups,
    indentation,
    alias_name,
    unsigned_int_bits,
    signed_int_bits,
    token_raw,
)

from .node_runtime import (
    RuleContext,
    execute_nodes,
    check_and_wrap_operand,
    register_family,
    execute_node,
    eval_condition,
    eval_exists,
    alignment_padding,
    eval_emit,
    eval_expr,
    case_matches,
    bits_fragment,
    eval_size,
    bits_of,
    int_value,
    integer_fits,
    integer_to_bytes,
)

__all__ = [
    "CompileError",
    "EmitError",
    "LiteralMismatchError",
    "NeedSyntaxError",
    "NeedTargetError",
    "OperandCountError",
    "OperandTypeError",
    "RuleConditionError",
    "RuleExecutionError",
    "RuleInstructionError",
    "SymbolPendingError",
    "UnknownNeedTypeError",
    "Lexer",
    "Token",
    "IDENT_RE",
    "KNOWN_NEED_TYPES",
    "NEED_NORMALIZE",
    "CONDITION_NAMES",
    "EMIT_MODES",
    "RESERVED_INSTRUCTION_NAMES",
    "HEX_BYTE_RE",
    "TypeInfo",
    "SubRegisterInfo",
    "RegisterInfo",
    "SymbolInfo",
    "WordInfo",
    "StackInfo",
    "InstructionNode",
    "MacroNode",
    "NeedNode",
    "LiteralNeedNode",
    "OperandNode",
    "RefNode",
    "IntNode",
    "StringNode",
    "ConditionNode",
    "CheckNode",
    "EmitNode",
    "ErrorNode",
    "OffNode",
    "OnNode",
    "CaseNode",
    "SwitchNode",
    "CallNode",
    "NonsfamilyNode",
    "MemskipNode",
    "MarkNode",
    "MultipleNode",
    "StrictNode",
    "CalcdistNode",
    "AssignNode",
    "PendingNode",
    "CompiledRule",
    "RuleNode",
    "Program",
    "expand_macro_instructions",
    "expand_macro_call",
    "parse_macro_call_args",
    "substitute_instruction",
    "substitute_tokens",
    "clone_instruction",
    "instruction_source",
    "tokens_to_source",
    "token_to_source",
    "needs_space",
    "compile_need_instruction",
    "compile_rule_body",
    "compile_rule_instruction",
    "compile_switch",
    "compile_case",
    "compile_on",
    "compile_emit",
    "compile_error",
    "parse_condition",
    "split_condition_operator",
    "parse_expr",
    "parse_case_value",
    "parse_bit_size",
    "parse_cbits_part",
    "split_spaces",
    "tokens_with_head",
    "strip_trailing_colon",
    "ensure_no_children",
    "ensure_no_args",
    "split_token_groups",
    "indentation",
    "alias_name",
    "unsigned_int_bits",
    "signed_int_bits",
    "token_raw",
    "RuleContext",
    "execute_nodes",
    "check_and_wrap_operand",
    "register_family",
    "execute_node",
    "eval_condition",
    "eval_exists",
    "alignment_padding",
    "eval_emit",
    "eval_expr",
    "case_matches",
    "bits_fragment",
    "eval_size",
    "bits_of",
    "int_value",
    "integer_fits",
    "integer_to_bytes",
]
