"""Módulo principal del compilador RIF.

Expone la interfaz pública para el Lexer, Parser, Linker, Packer, Compiler
y los modelos de datos esenciales que estructuran el flujo del framework.
"""

from .errors import RIFError, LexError, ParseError, PackError, Errors, EndSignal, end
from .lexer import Lexer
from .parser import Parser, collect_codegen
from .linker import Linker, link_file, build_file
from .packer import Packer, build_pack, pack_file
from .resolver import PlaceholderResolver, resolve_placeholders
from .compiler import Compiler, compile_instruction
from .models import (
    Token,
    Program,
    BitVariable,
    DataDefinitionInfo,
    HeaderBlock,
    HeadersInfo,
    Section,
    Statement,
    MemoryInfo,
    MemoryRegion,
    PackerConfig,
    PackedResult,
    LinkBlock,
    BinaryLinkResult,
    TYPES_MAP,
    TypeInfo,
    Line,
    Err,
    Expr,
    IDENT,
    Operators,
    Operator,
    RuleIndicator,
    TypeDefinition,
    TypesInfo,
    OperatorBinding,
    REG,
    DATA,
    EmitChunk,
    EmitInstruction,
    FlowInstruction,
    CodegenInfo,
    Placeholder,
    PluginContext,
    PlaceholderResolution,
    Relocation,
    ResolvedPlaceholder,
    OperandValue,
    CompileResult,
)

__all__ = [
    "RIFError",
    "LexError",
    "ParseError",
    "PackError",
    "Errors",
    "EndSignal",
    "end",
    "Lexer",
    "Parser",
    "collect_codegen",
    "Linker",
    "link_file",
    "build_file",
    "Packer",
    "build_pack",
    "pack_file",
    "PlaceholderResolver",
    "resolve_placeholders",
    "Compiler",
    "compile_instruction",
    "Token",
    "Program",
    "BitVariable",
    "DataDefinitionInfo",
    "HeaderBlock",
    "HeadersInfo",
    "Section",
    "Statement",
    "MemoryInfo",
    "MemoryRegion",
    "PackerConfig",
    "PackedResult",
    "LinkBlock",
    "BinaryLinkResult",
    "TYPES_MAP",
    "TypeInfo",
    "Line",
    "Err",
    "Expr",
    "IDENT",
    "Operators",
    "Operator",
    "RuleIndicator",
    "TypeDefinition",
    "TypesInfo",
    "OperatorBinding",
    "REG",
    "DATA",
    "EmitChunk",
    "EmitInstruction",
    "FlowInstruction",
    "CodegenInfo",
    "Placeholder",
    "PluginContext",
    "PlaceholderResolution",
    "Relocation",
    "ResolvedPlaceholder",
    "OperandValue",
    "CompileResult",
]
